FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY . .

ARG BOT_TOKEN
ARG ADMIN_IDS
ARG REDIS_HOST
ARG REDIS_PORT
ARG TOPN_DB_BASE_URL

ENV BOT_TOKEN=${BOT_TOKEN}
ENV ADMIN_IDS=${ADMIN_IDS}
ENV REDIS_HOST=${REDIS_HOST}
ENV REDIS_PORT=${REDIS_PORT}
ENV TOPN_DB_BASE_URL=${TOPN_DB_BASE_URL}

CMD ["python", "main.py"]
